spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: messaging-topic
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.kcell.testtask.messaging.serializer.KafkaProducerValueSerializer

  graphql:
    graphiql:
      enabled: true