spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: messaging-topic
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
